# -*- coding: utf-8 -*-
"""predict new user of telecommunication system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CZx_XV8Q3spbQlrCDdDltsqqRfVnyN0
"""

# Commented out IPython magic to ensure Python compatibility.
#load required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # Import seaborn
from sklearn import preprocessing
# %matplotlib inline

#Load the required data
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/teleCust1000t.csv')
df.head()

#Data visualization and analyisis
df['custcat'].value_counts() # Corrected 'custcatt' to 'custcat'

# Generate the histogram for 'income' and set labels
ax_list = df.hist(column='income', bins=50)
ax = ax_list[0][0] # Access the AxesSubplot object
ax.set_xlabel('Income')
ax.set_ylabel('Frequency')
ax.set_title('Distribution of Income') # Add a title for clarity

df.columns # Corrected 'colums' to 'columns'
X = df[['region', 'tenure','age', 'marital', 'address', 'income', 'ed', 'employ','retire', 'gender', 'reside']] .values  #.astype(float)
X[0:5]
y=df['custcat'].values
y[0:5]

#Normalizing the data
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float)) # Corrected 'standardscaler' to 'StandardScaler' and 'x' to 'X'

#Train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=4) # Changed 'x' to 'X'
print('Train set:', x_train.shape, y_train.shape)
print('test set:',x_test.shape, y_train.shape)

#Classification
from sklearn.neighbors import KNeighborsClassifier
k=4
neigh=KNeighborsClassifier(n_neighbors=k).fit(x_train, y_train)
neigh
yhat=neigh.predict(x_test)
yhat[0:5]

#Accuracy evaluation
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

"""### Distribution of Customer Categories (`custcat`)

Let's visualize the distribution of our target variable, `custcat`. This will show us how many customers fall into each of the four categories.
"""

plt.figure(figsize=(8, 6))
sns.countplot(x='custcat', data=df, palette='viridis')
plt.title('Distribution of Customer Categories')
plt.xlabel('Customer Category')
plt.ylabel('Number of Customers')
plt.show()

"""### Distributions of Other Numerical Features

Next, let's look at the distributions of other numerical features like `tenure`, `age`, and `employ` using histograms.
"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.histplot(df['tenure'], bins=30, kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Distribution of Tenure')
axes[0].set_xlabel('Tenure (months)')
axes[0].set_ylabel('Frequency')

sns.histplot(df['age'], bins=30, kde=True, ax=axes[1], color='lightcoral')
axes[1].set_title('Distribution of Age')
axes[1].set_xlabel('Age (years)')
axes[1].set_ylabel('Frequency')

sns.histplot(df['employ'], bins=30, kde=True, ax=axes[2], color='lightgreen')
axes[2].set_title('Distribution of Employment Years')
axes[2].set_xlabel('Years Employed')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""### Relationship Between Numerical Features and `custcat`

To see how numerical features vary across customer categories, let's use box plots for `income` and `tenure` against `custcat`.
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.boxplot(x='custcat', y='income', data=df, palette='pastel', ax=axes[0])
axes[0].set_title('Income by Customer Category')
axes[0].set_xlabel('Customer Category')
axes[0].set_ylabel('Income')

sns.boxplot(x='custcat', y='tenure', data=df, palette='pastel', ax=axes[1])
axes[1].set_title('Tenure by Customer Category')
axes[1].set_xlabel('Customer Category')
axes[1].set_ylabel('Tenure')

plt.tight_layout()
plt.show()

"""### Relationship Between Categorical Features and `custcat`

Finally, let's examine the relationship between a categorical feature like `gender` and `custcat` using a count plot, separated by gender.
"""

plt.figure(figsize=(10, 6))
sns.countplot(x='custcat', hue='gender', data=df, palette='coolwarm')
plt.title('Customer Categories by Gender')
plt.xlabel('Customer Category')
plt.ylabel('Number of Customers')
plt.legend(title='Gender', labels=['Female', 'Male']) # Assuming 0 for Female, 1 for Male or similar binary encoding
plt.show()

import pandas as pd
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/teleCust1000t.csv')
df.head(20)